### ISSUE TITLE
Impossible to assign permission

### ISSUE THREAD

**Issue by facilinfo** [joselfonseca/laravel-admin-blog#1]
Hello, 

Everything is ok when installing except the last step when I try to assign the blog-admin permission to a user. The button does nothing.

Thanks for your help.

**Comment by joselfonseca** [comment]
Hey there!, have you created the permission in the permissions UI interface? What button are you referring to, the one in the sidebar to access the blog admin? if you can provide screen shoots it would be really helpful so i can see what is going on. Thanks!

**Comment by facilinfo** [comment]
![permission_error](https://cloud.githubusercontent.com/assets/16045967/11564502/73dd37b6-99d1-11e5-8a66-3010b7feafaf.png)

Yes, I created the permission from the UI.

Thanks

**Comment by joselfonseca** [comment]
Do you have any error in the chrome developer console? that is a Javascript call, can you see if you have any error there please.

**Comment by facilinfo** [comment]
![permission error2](https://cloud.githubusercontent.com/assets/16045967/11565644/c2e99336-99d6-11e5-8184-c11d53bae0dd.png)

Yes, I have this 404 error in Firefox. 

The url is not correct :
 http://localhost/backend/roles/permissions

instead of :
 http://localhost/lab/testBlog88/public/backend/roles/permissions

Thanks

**Comment by joselfonseca** [comment]
Ok, it asumes you set up a virtual host for the site, instead of using localhost. he have 2 options here.

1. Create a virtual host for that project, that should fix your particular issue. 
2. Create an issue in https://github.com/joselfonseca/laravel-admin/ and i will add the base url later this week.  it should be added here https://github.com/joselfonseca/laravel-admin/blob/master/resources/assets/js/app.js#L47 and then the assets need to be re compiled and published again.

I would recommend creating the virtual host for your project to get it working now. and i will add the issue in the Laravel Admin Repo to fix that some time this week as soon as i get the chance.

Please let me know.

Thanks

**Comment by joselfonseca** [comment]
I just uploaded a new tag, please run composer update and it should download https://github.com/joselfonseca/laravel-admin/releases/tag/0.4.7 then publish the assets again by running `php artisan vendor:publish --tag="la-public" --force` 

That should take care of it.
